### ISSUE TITLE
[Bug] Docker image not working

### ISSUE THREAD

**Issue by caesarchad** [libra/libra#1479]
# 🐛 Bug

The scripts under docker folder cannot work properly. The docker image won't run as expected.

## To reproduce

**Code snippet to reproduce**
```rust
git clone https://github.com/libra/libra.git
cd libra
./docker/validator/build.sh
./docker/validator/run.sh
./docker/mint/build.sh
./docker/mint/run.sh
```

**Stack trace/error message**
```
[vm_config]
  [vm_config.publishing_options]
    type = "Locked"
    whitelist = [
        "1cf66b5f5c911e80dad222b8ee8dfe3ad4830f75bb412ba12ea8e429203d9c83",
        "5ee07d4ac1ecf88f1b41c2c458f15699fe9d811c61563338253b3807b75c04c1",
        "6aabc87f543f85e10216432d02b0251297d4c7723e906de481dfa04b057c2371",
        "a2180395d1632a0793f34e8a8a6be20b3b03bdceee35affe8c751fc8467b73a4",
    ] -e SEED_PEERS=[seed_peers]
8deeeaed65f0cd7484a9e4e5ac51fbac548f2f71299a05e000156031ca78fb9f = ["/ip4/172.18.0.10/tcp/6180"] -v /home/leon/projects/libra/docker/validator/../../terraform/validator-sets/dev//val/network_peers.config.toml:/opt/libra/etc/network_peers.config.toml -v /home/leon/projects/libra/docker/validator/../../terraform/validator-sets/dev//consensus_peers.config.toml:/opt/libra/etc/consensus_peers.config.toml -v /home/leon/projects/libra/docker/validator/../../terraform/validator-sets/dev//genesis.blob:/opt/libra/etc/genesis.blob -e NETWORK_KEYPAIRS=network_signing_private_key = "f9e1b4bd35cff88f047043aebedfbd310bb6ca762040ac51c28203fb1873e539"
network_signing_public_key = "66535c0f4f9242ea8f9ff7f68b4f50b7c9d8e7961a41cf216124b33a325505ff"
network_identity_private_key = "78fea3aa16bf4a9c6471aeaa6fc3e0427d311503a31fe37f0245e30addf14e53"
network_identity_public_key = "882a6058c64664e59415d1692b8ecbe976665b4549631c7ff15e6fbce3e2e50e" -e CONSENSUS_KEYPAIR=consensus_private_key = "2bb04f975864ebab903123d6ba517ddd4b145efb28f728968e0d7437fc750977"
consensus_public_key = "1faf7c0c4dd0b3025e2aa5635395aac947b659dff188a0380e6ead27a2c33a1a" --ip 172.18.0.13 --network testnet --publish 8000:8000 libra_e2e:latest
I1023 09:27:19.254236 139977534994176 common/executable-helpers/src/helpers.rs:12] Loading node config from: node.config.toml
C1023 09:27:19.505408 139977534994176 common/crash-handler/src/lib.rs:36] details = '''panicked at 'Cannot open config file "fullnode_peers.config.toml"', config/src/config.rs:816:49'''
backtrace = '''
stack backtrace:
   0:     0x5576698f28c7 - backtrace::backtrace::libunwind::trace::ha30f9fc618e8c985
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
                           backtrace::backtrace::trace_unsynchronized::h505aee33efb7fa48
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
                           backtrace::backtrace::trace::h3526715cd5502058
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:53
   1:     0x5576698f19d3 - backtrace::capture::Backtrace::create::h4fa6ead0fac59fef
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/capture.rs:164
                           backtrace::capture::Backtrace::new::h8a5814f08fb450bc
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/capture.rs:128
   2:     0x557669581b63 - crash_handler::handle_panic::h1d7b31baa8818584
                               at common/crash-handler/src/lib.rs:33
   3:     0x557669581ae9 - crash_handler::setup_panic_handler::{{closure}}::he4009360fbe9f8bb
                               at common/crash-handler/src/lib.rs:25
   4:     0x5576699155ac - std::panicking::rust_panic_with_hook::h3c82d7c1012a629a
                               at src/libstd/panicking.rs:477
   5:     0x557669915062 - std::panicking::continue_panic_fmt::h2ed10c5154e7cc64
                               at src/libstd/panicking.rs:380
   6:     0x557669914fbc - std::panicking::begin_panic_fmt::hbdfc4aaa79ddf41e
                               at src/libstd/panicking.rs:335
   7:     0x557669571e07 - libra_config::config::PersistableConfig::load_config::{{closure}}::h7b8b2e3b6b37c60b
                               at /libra/<::std::macros::panic macros>:9
                           core::result::Result<T,E>::unwrap_or_else::hc3bd4953d1f4de6a
                               at /rustc/224f0bc90c010b88ca6ec600c9b02f6e3638d78e/src/libcore/result.rs:818
                           libra_config::config::PersistableConfig::load_config::h2cecb90eafbf605f
                               at /libra/config/src/config.rs:816
   8:     0x5576694e41d0 - libra_config::config::NetworkConfig::load::h9ab9027e59507036
                               at /libra/config/src/config.rs:366
   9:     0x5576694e3c2a - libra_config::config::NodeConfig::load::h28e29c46e198518d
                               at /libra/config/src/config.rs:569
  10:     0x5576694e348b - executable_helpers::helpers::load_config_from_path::hc5720294e2978dec
                               at common/executable-helpers/src/helpers.rs:13
  11:     0x5576694e3728 - executable_helpers::helpers::setup_executable::h37de963317edb266
                               at common/executable-helpers/src/helpers.rs:43
  12:     0x55766896fb62 - libra_node::main::hbf0e82434f738c86
                               at libra-node/src/main.rs:51
  13:     0x5576689642b3 - std::rt::lang_start::{{closure}}::h9d330b3283010f1b
                               at /rustc/224f0bc90c010b88ca6ec600c9b02f6e3638d78e/src/libstd/rt.rs:64
  14:     0x557669914ef3 - std::rt::lang_start_internal::{{closure}}::h98b7eaad41cfe50c
                               at src/libstd/rt.rs:49
                           std::panicking::try::do_call::h0837b54a303dffcc
                               at src/libstd/panicking.rs:292
  15:     0x5576699198fa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  16:     0x557669915a7d - std::panicking::try::h7a6139268f1b3256
                               at src/libstd/panicking.rs:271
                           std::panic::catch_unwind::hbcfdb3081816cb9a
                               at src/libstd/panic.rs:394
                           std::rt::lang_start_internal::hdbd4042f5aaab85e
                               at src/libstd/rt.rs:48
  17:     0x55766896ff98 - main
  18:     0x7f4f0ff7709b - __libc_start_main
  19:     0x55766896270a - _start
  20:                0x0 - <unknown>
'''

```

## Expected Behavior

Docker image begin to run 
## System information

**Please complete the following information:**
-   libra from the master branch
-  rustc 1.39.0-beta.6 (224f0bc90 2019-10-15)

-  Ubuntu 18.04 LTS

**Comment by opsguy** [comment]
Thanks for the report, will try to take a look at this next week.

**Comment by princeulrich2** [comment]
I'm also facing the same issue on Ubuntu 18.04... were you able to solve it?
