### ISSUE TITLE
[Bug] Build error occured when  compiling 'network'

### ISSUE THREAD

**Issue by gurrpi** [libra/libra#18]
# 🐛 Bug

## To reproduce
`RUST_BACKTRACE=1 cargo run -p client`

** Stack trace/error message **
```
$ RUST_BACKTRACE=1 cargo run -p client
   Compiling network v0.1.0 (/Users/daehyun/Documents/Workspace/references/libra/network)
   Compiling slog-envlogger v2.1.0
   Compiling hyper v0.12.30
   Compiling prost-build v0.5.0
   Compiling prost-types v0.5.0
error: failed to run custom build command for `network v0.1.0 (/Users/daehyun/Documents/Workspace/references/libra/network)`

Caused by:
  process didn't exit successfully: `/Users/daehyun/Documents/Workspace/references/libra/target/debug/build/network-267ca6ea5a198f61/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: <protobuf_codegen::field::FieldGen as core::clone::Clone>::clone
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libcore/result.rs:827
  10: build_script_build::main
             at network/build.rs:16
  11: std::rt::lang_start::{{closure}}
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  14: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
  16: build_script_build::main

warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Expected Behavior
Build success.

## System information

**Please complete the following information:**
- Libra Version: commit`5e034dd
- Rust Version: rustc 1.36.0-nightly (50a0defd5 2019-05-21)
- Computer OS: macOS 10.14.4

**Comment by gurrpi** [comment]
As mentioned related [problem](https://community.libra.org/t/networking-in-libra-core/54/6?u=gurrpi), installing protobuf compiler resolves this issue. (`brew install protobuf`)
