### ISSUE TITLE
[Bug] failed to run cargo install --path libra_node/

### ISSUE THREAD

**Issue by LaurenceM10** [libra/libra#224]
# 🐛 Bug

Error: failed to run custom build command for `grpcio-sys v0.4.4`
Error: failed to run custom build command for `network v0.1.0 (/home/libra/network)`
Error: failed to run custom build command for `snappy-sys v0.1.0 (https://github.com/busyjay/rust-snappy.git?branch=static-link#8c12738b)`
Error: failed to compile `libra_node v0.1.0 (/home/libra/libra_node)`, intermediate artifacts can be found at `/home/libra/target`

## To reproduce

```
cargo install --path libra_node/
```

** Stack trace/error message **
```
cargo install --path libra_node/
  Installing libra_node v0.1.0 (/home/libra/libra_node)
    Updating crates.io index
    Updating git repository `https://github.com/pingcap/rust-rocksdb.git`
    Updating git repository `https://github.com/alexcrichton/bzip2-rs.git`
    Updating git repository `https://github.com/busyjay/lz4-rs.git`
    Updating git repository `https://github.com/busyjay/rust-snappy.git`
    Updating git repository `https://github.com/gyscos/zstd-rs.git`
   Compiling network v0.1.0 (/home/libra/network)
   Compiling grpcio-sys v0.4.4
   Compiling snappy-sys v0.1.0 (https://github.com/busyjay/rust-snappy.git?branch=static-link#8c12738b)
   Compiling ring v0.14.6
error: failed to run custom build command for `network v0.1.0 (/home/libra/network)`

Caused by:
  process didn't exit successfully: `/home/libra/target/release/build/network-847f1a8c85eec059/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `grpcio-sys v0.4.4`

Caused by:
  process didn't exit successfully: `/home/libra/target/release/build/grpcio-sys-14c13c5fbbed61a7/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
running: "cmake" "/home/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.4/grpc" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DCMAKE_INSTALL_PREFIX=/home/libra/target/release/build/grpcio-sys-74a7f2a6459dd69f/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /home/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `snappy-sys v0.1.0 (https://github.com/busyjay/rust-snappy.git?branch=static-link#8c12738b)`

Caused by:
  process didn't exit successfully: `/home/libra/target/release/build/snappy-sys-a75f6041ac6308ce/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/developer/.cargo/git/checkouts/rust-snappy-0ed33e4b7b96fc57/8c12738/snappy-sys/snappy" "-DCMAKE_INSTALL_PREFIX=/home/libra/target/release/build/snappy-sys-f1a2ab944bef784b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"

--- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /home/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `libra_node v0.1.0 (/home/libra/libra_node)`, intermediate artifacts can be found at `/home/libra/target`

Caused by:
  build failed

```

## Expected Behavior

 Install the node binary

## System information

- Master branch -> Commit 7898828
- rustc 1.36.0-nightly
- Ubuntu 18.04.2

**Comment by bmwill** [comment]
Looking at the error message you've provided it looks like you don't have the required dependencies installed. In order to build the project you need `protoc`, `cmake`, and `go` installed per the instructions on the [developer site](https://developers.libra.org/docs/my-first-transaction#setup-libra-core).

**Comment by LaurenceM10** [comment]
@bmwill After installing these dependencies


error: failed to run custom build command for `network v0.1.0 (/.../libra/network)`

```
Caused by:
  process didn't exit successfully: `/.../libra/target/release/build/network-847f1a8c85eec059/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/proto/network.proto
cargo:rerun-if-changed=src/proto/mempool.proto
cargo:rerun-if-changed=src/proto/consensus.proto

--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `libra_node v0.1.0 (/.../libra/libra_node)`, intermediate artifacts can be found at `/.../libra/target`

Caused by:
  build failed

```

**Comment by kphfb** [comment]
It still appears that you may not have protoc installed.  Can you run protoc --version from the command line and see if you have it installed?

**Comment by bmwill** [comment]
The external dependencies needed to build Libra have been simplified and should only require Rust now so this shouldn't be an issue anymore on master. If it is, please let us know.
