### ISSUE TITLE
[Bug]failed to build when 'export GO111MODULE=on'

### ISSUE THREAD

**Issue by btspoony** [libra/libra#228]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```shell
export GO111MODULE=on
```
when I commented it in the .bash_profile, the compilation process would to be succeed

** Stack trace/error message **
```
--- stderr
go: cannot find main module; see 'go help modules'
make[3]: *** [third_party/boringssl/crypto/err/err_data.c] Error 1
make[3]: *** Deleting file `third_party/boringssl/crypto/err/err_data.c'
make[2]: *** [third_party/boringssl/crypto/err/CMakeFiles/err.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/grpc.dir/rule] Error 2
make: *** [grpc] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/bibi/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
```

## Expected Behavior

wanted to build the system successfully

## System information

**Please complete the following information:**
- libra commit: 737839b744794c0ca3be3db2934de7ebf056639a
- rustc 1.36.0-nightly (50a0defd5 2019-05-21)
- macOS 10.14.5

**Comment by tenghuanhe** [comment]
how do you find this? You saved my day!!
