### ISSUE TITLE
build failed caused by jemalloc

### ISSUE THREAD

**Issue by fxsjy** [libra/libra#23]
### 
thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /home/ec2-user/.cargo/registry/src/github.com-1ecc629
b9ec823/jemalloc-sys-0.1.8/build.rs:286:19
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

OS: Linux  4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fxsjy** [comment]
--- stderr
thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /home/ec2-user/.cargo/registry/src/github.com-1ecc6299
b9ec823/jemalloc-sys-0.1.8/build.rs:286:19
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: build_script_build::run
             at ./build.rs:286
   8: build_script_build::main
             at ./build.rs:234
   9: std::rt::lang_start::{{closure}}
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  12: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  13: std::rt::lang_start
             at /rustc/50a0defd5a93523067ef239936cc2e0755220904/src/libstd/rt.rs:64
  14: main
  15: __libc_start_main
  16: _start

**Comment by fxsjy** [comment]
I changed from CentOS to  Ubuntu, and then it works.
