### ISSUE TITLE
[Bug] Crash in network::discovery module due to unexpected discovery note.

### ISSUE THREAD

**Issue by bothra90** [libra/libra#2477]
# 🐛 Bug

**Stack trace/error message**
```
C0207 13:53:51.540858 139829006300928 common/crash-handler/src/lib.rs:38] details = '''
panicked at 'assertion failed: `(left != right)`
  left: `876f6d031beba522f7a42b425f25598a672156b89aa4b75c9ae397f4e59a538d`,
 right: `876f6d031beba522f7a42b425f25598a672156b89aa4b75c9ae397f4e59a538d`', network/src/protocols/discovery/mod.rs:333:21'''
backtrace = '''
stack backtrace:
   0:     0x55edd24aa5d7 - backtrace::backtrace::libunwind::trace::h98a0578fa2d95698
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
                           backtrace::backtrace::trace_unsynchronized::ha0ca25af83675209
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
                           backtrace::backtrace::trace::h567fc8e6753f4e36
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:53
   1:     0x55edd24a9803 - backtrace::capture::Backtrace::create::h6d19f686ae27ede7
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/capture.rs:164
                           backtrace::capture::Backtrace::new::hfdf48bb8a3314f07
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/capture.rs:128
   2:     0x55edd219d6f3 - crash_handler::handle_panic::h6f2af6e7e02686ed
                               at common/crash-handler/src/lib.rs:35
   3:     0x55edd219d679 - crash_handler::setup_panic_handler::{{closure}}::hd2e342ed2821e9b8
                               at common/crash-handler/src/lib.rs:27
   4:     0x55edd24e4eb0 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:468
   5:     0x55edd24e497e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
   6:     0x55edd24e48bf - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
   7:     0x55edd1d65778 - network::protocols::discovery::Discovery<TTicker>::reconcile::{{closure}}::h1d66e8fac1dbc800
                               at network/src/protocols/discovery/mod.rs:333
                           <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::hff2dca83ea9e687d
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
                           std::future::set_task_context::h40ba017f0d96ea01
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
                           <std::future::GenFuture<T> as core::future::future::Future>::poll::hbcfaec5d2880b9e6
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
                           std::future::poll_with_tls_context::{{closure}}::h3d6576b83de3550e
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
                           std::future::get_task_context::h02f2551c04bc4723
```

## Expected Behavior
The panic suggests that the node's discovery module received a note with higher epoch number for itself than it had advertised. This is an unexpected condition and suggests a bug in the code.

**Comment by bothra90** [comment]
The situation above is possible when a validator is restarted on a node whose clock is behind than the node it was previously started on. Instead of issuing a `panic!` when we encounter this situation, it's better and safe to issue a new note with an epoch number higher than the one observed in the received discovery note.
