### ISSUE TITLE
[Bug] Starting Libra Swarm - "Failed to get account state from validator"

### ISSUE THREAD

**Issue by acharb** [libra/libra#2669]
# 🐛 Bug
Following the steps here: https://developers.libra.org/docs/run-move-locally
ends up with error: 
```
Failed to get account state from validator, error: grpc-status: Unavailable, grpc-message: "error trying to connect: tcp connect error: Connection refused (os error 61)"
```

## To reproduce

$ cargo run -p libra-swarm -- -s

When completed gives the message:

```
To run the Libra CLI client in a separate process and connect to the validator nodes you just spawned, use this command:
	cargo run --bin cli -- -a localhost -p 54735 -m "/var/folders/r4/tccnvyv10b524jq41981yk4c0000gn/T/1f1d194c23dce72af6bc6c24c75b5062/mint.key"
```

$ cargo run --bin cli -- -a localhost -p 54735 -m "/var/folders/r4/tccnvyv10b524jq41981yk4c0000gn/T/1f1d194c23dce72af6bc6c24c75b5062/mint.key"

gives:

```
E0221 19:37:16.016948 4812291520 client/cli/src/client_proxy.rs:914] Failed to get account state from validator, error: grpc-status: Unavailable, grpc-message: "error trying to connect: tcp connect error: Connection refused (os error 61)"
C0221 19:37:17.944074 4812291520 common/crash-handler/src/lib.rs:38] details = '''panicked at 'Not able to connect to validator at localhost:55988. Error: grpc-status: Unavailable, grpc-message: "error trying to connect: tcp connect error: Connection refused (os error 61)"', client/cli/src/main.rs:113:13'''
backtrace = '''
stack backtrace:
   0:        0x10e30a2ed - backtrace::backtrace::libunwind::trace::hb1a3c80c2a209c2c
                               at /Users/aleccharbonneau/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
                           backtrace::backtrace::trace_unsynchronized::hfc792b8bb2b48548
                               at /Users/aleccharbonneau/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   1:        0x10e30a273 - backtrace::backtrace::trace::habeca48243085820
                               at /Users/aleccharbonneau/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:53
   2:        0x10e30f0c7 - backtrace::capture::Backtrace::create::h5e91f51a5f388779
                               at /Users/aleccharbonneau/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/capture.rs:164
   3:        0x10e30f006 - backtrace::capture::Backtrace::new::h00ba5430e2788e5f
                               at /Users/aleccharbonneau/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/capture.rs:128
   4:        0x10cda7fe9 - crash_handler::handle_panic::h6182d89e0a97d627
                               at common/crash-handler/src/lib.rs:35
   5:        0x10cda6fc9 - crash_handler::setup_panic_handler::{{closure}}::h6aab175a84fe6400
                               at common/crash-handler/src/lib.rs:27
   6:        0x10e3c70dc - std::panicking::rust_panic_with_hook::h9db77b22c2255a16
                               at src/libstd/panicking.rs:468
   7:        0x10e3c6b99 - std::panicking::continue_panic_fmt::h2dfa3a5b90265361
                               at src/libstd/panicking.rs:373
   8:        0x10e404eff - std::thread::local::fast::Key<T>::try_initialize::ha9c626eb0a4b75ab
   9:        0x10cd7f31a - cli::main::{{closure}}::h18553181e131f71d
                               at client/cli/src/main.rs:113
  10:        0x10cd807de - core::result::Result<T,E>::unwrap_or_else::h838bcfc2446e9e86
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:818
  11:        0x10cda33e9 - cli::main::hb7be9d2e483d9912
                               at client/cli/src/main.rs:110
  12:        0x10cda6172 - std::rt::lang_start::{{closure}}::hbfb4127849379cf5
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  13:        0x10e3c6a68 - std::rt::lang_start_internal::{{closure}}::hccd7db6d8a0ebab5
                               at src/libstd/rt.rs:48
                           std::panicking::try::do_call::hd5a3af8d00c06681
                               at src/libstd/panicking.rs:287
  14:        0x10e3cee7f - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  15:        0x10e3c739e - std::panicking::try::h7a0bd4c078131d2f
                               at src/libstd/panicking.rs:265
                           std::panic::catch_unwind::h75c3fbe62776ab10
                               at src/libstd/panic.rs:396
                           std::rt::lang_start_internal::haa52aabac43378ff
                               at src/libstd/rt.rs:47
  16:        0x10cda6152 - std::rt::lang_start::h9d915099b2d84734
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  17:        0x10cda6102 - cli::Args::augment_clap::h5203eda7137ec876
```

## System information

- rustc 1.40.0 
- Mac OSX 10.15.3

Would love to start playing around with Move so would appreciate any help thanks!

**Comment by bmwill** [comment]
There's a lot thats changed since this was filed (e.g. we don't use gRPC anymore). If you're still hitting this issue with the latest code then please reopen this issue.
