### ISSUE TITLE
[Bug] "cargo run -p libra-swarm -- -s" Unable to build all workspace binaries.

### ISSUE THREAD

**Issue by AntoineMkr** [libra/libra#3713]
# 🐛 Bug

After installing Libra without any problems, I wanted to launch a local node to play with.
But I encountered that error:
**Stack trace/error message**
```
thread 'main' panicked at '
    Unable to build all workspace binaries. Cannot continue running tests.

    Try running 'cargo build --all --bins --exclude cluster-test' yourself.
', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
logs located at "/tmp/7e2ae50ceb175cc22182c4863eeecf7a"
```
So I entered `cargo build --all --bins --exclude cluster-test`
That command made my computer very laggy, and it took a while to achieve. The output is:
```
# Compiling 

error: linking with `cc` failed: exit code: 1
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" 

# followed by all the deps pathes like 
"/home/USERNAME/.rustup/toolchains/1.43.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
"/home/USERNAME/libra/target/debug/deps/investigate-73900e6e17357af2.1joi3ianzc265m37.rcgu.o" "/home/USERNAME/libra/target/debug/deps/investigate-73900e6e17357af2.1nz7oau12r5bgl01.rcgu.o" 
# and so on... It does a lot of pathes

"-Wl,-Bdynamic" "-lstdc++" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: collect2: fatal error: ld terminated with signal 9 [Processus arrêté]
          compilation terminated.
error: aborting due to previous error

error: could not compile `libra-fuzzer`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
# tries to compile the next packages, returns the same error 
error: aborting due to previous error

error: could not compile `libra-fuzz`.
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
## To reproduce

**Code snippet to reproduce**
```rust
# I followed the tutorial
git clone https://github.com/libra/libra.git && cd libra
git checkout testnet
./scripts/dev_setup.sh
# which returned 
Finished installing all dependencies.
You should now be able to build the project by running:
	source /home/USERNAME/.cargo/env
	cargo build
# Which I did
./scripts/cli/start_cli_testnet.sh

# So until here everything went fine. Problems arrive here:
cargo run -p libra-swarm -- -s
```

## System information
**Please complete the following information:**
-  ubuntu 18.04

**Comment by wqfish** [comment]
pretty sure you ran out of memory on your machine

**Comment by AntoineMkr** [comment]
Hi thanks for your answer. How much free space of hard drive and/or Gb of RAM would I need ? Still have more than 50Gb on hardrive and I've got 8gb of RAM

**Comment by wqfish** [comment]
I'm not sure... 8gb doesn't sound too little. Maybe try reducing the cargo parallelism and see...

**Comment by AntoineMkr** [comment]
Mmmh I don't know, I tried the `cargo run -p libra-swarm` command with the -j n parameter (number of jobs/CPU cores), still have the error. When the processus arrives at "building workspace binaires", it starts to use 100% of all my 8 CPU cores (don't know why since I added the -j 4 parameter) and got some spikes at 95% of the RAM being used.

**Comment by AntoineMkr** [comment]
Ok it seems that spamming `cargo build --all --bins --exclude cluster-test` works BUT if only it was that easy:
`INFO 2020-05-06 11:28:35 execution/executor/src/db_bootstrapper.rs:72 Genesis commited.
INFO 2020-05-06 11:28:35 common/workspace-builder/src/lib.rs:16 Building project binaries
INFO 2020-05-06 11:28:35 common/workspace-builder/src/lib.rs:30 Finished building project binaries
Wait for startup attempt: 0 of 120
Health check on node '0'
Error querying metrics for node '0'
Wait for startup attempt: 1 of 120
Health check on node '0'
Node '0' is healthy
INFO 2020-05-06 11:28:36 libra-swarm/src/swarm.rs:370 Successfully launched Swarm
To run the Libra CLI client in a separate process and connect to the validator nodes you just spawned, use this command:
	cargo run --bin cli -- -u http://localhost:37533 -m "/tmp/f1cc230737bca9404a96d005a73e0130/mint.key"
To run transaction generator run:
	cargo run -p cluster-test -- --mint-file "/tmp/f1cc230737bca9404a96d005a73e0130/mint.key" --swarm --peers "localhost:37533" --emit-tx --workers-per-ac 1
Loading client...
ERROR 2020-05-06 11:28:37 common/crash-handler/src/lib.rs:38 details = '''panicked at 'called `Option::unwrap()` on a `None` value', client/cli/src/main.rs:85:9'''
backtrace = '''
   0:     0x55921f121b9d - backtrace::backtrace::libunwind::trace::h9134a8721401234b
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
                           backtrace::backtrace::trace_unsynchronized::h74e140a14a1f1dae
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   1:     0x55921f121b1e - backtrace::backtrace::trace::h1defcd00b9a88cfd
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:53
   2:     0x55921f11930d - backtrace::capture::Backtrace::create::h143b1894b872deb6
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:164
   3:     0x55921f119225 - backtrace::capture::Backtrace::new::hca3c1e6f9d02b01f
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:128
   4:     0x55921f10ba9b - crash_handler::handle_panic::hb2036a4f31d31476
                               at common/crash-handler/src/lib.rs:35
   5:     0x55921f10ca56 - crash_handler::setup_panic_handler::{{closure}}::h0a96609e47205d30
                               at common/crash-handler/src/lib.rs:27
   6:     0x55921fed9005 - std::panicking::rust_panic_with_hook::hb976084785e50594
                               at src/libstd/panicking.rs:474
   7:     0x55921fed8b1b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
   8:     0x55921fefc021 - core::panicking::panic_fmt::h45f7d6868edb5678
                               at src/libcore/panicking.rs:85
   9:     0x55921fefbf6d - core::panicking::panic::h0fd4184f909d9498
                               at src/libcore/panicking.rs:52
  10:     0x55921f06156d - core::option::Option<T>::unwrap::h44e30e3866aac13c
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/macros/mod.rs:10
  11:     0x55921f04ef23 - cli::main::{{closure}}::hd38aa830d042239e
                               at client/cli/src/main.rs:85
  12:     0x55921f05ee9a - core::option::Option<T>::unwrap_or_else::h7da509af933eda82
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/option.rs:428
  13:     0x55921f049945 - cli::main::hf2ed74c0ff11d786
                               at client/cli/src/main.rs:84
  14:     0x55921f04747b - std::rt::lang_start::{{closure}}::hbbc6ec82d3b45aa9
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  15:     0x55921fed89f3 - std::rt::lang_start_internal::{{closure}}::hc0a1280e68ffc5da
                               at src/libstd/rt.rs:52
                           std::panicking::try::do_call::h1d43a4d29f303ef5
                               at src/libstd/panicking.rs:303
  16:     0x55921fee1947 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  17:     0x55921fed944c - std::panicking::try::h5ef738612ab0072d
                               at src/libstd/panicking.rs:281
                           std::panic::catch_unwind::h1df9a04c7f1c6fc3
                               at src/libstd/panic.rs:394
                           std::rt::lang_start_internal::h97d4af4643f4b0e4
                               at src/libstd/rt.rs:51
  18:     0x55921f047457 - std::rt::lang_start::hfb97c0bc01172405
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  19:     0x55921f04cbea - main
  20:     0x7fb462bd5b97 - __libc_start_main
  21:     0x55921f045d2a - _start
  22:                0x0 - <unknown>
'''

Exit client.
Exit libra-swarm.
`

**Comment by Soleone** [comment]
I get a similar error on OSX 10.15.4 on a MacBook Pro 2015 with 16gb RAM and currently 16gb of free space on the SSD drive, using Rust 1.43.0 following [these basic instructions](https://developers.libra.org/docs/run-local-network):

```
/workspace/opensource/libra(testnet) ➜ cargo run -p libra-swarm -- -s
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/libra-swarm -s`
INFO 2020-05-12 04:50:18 libra-swarm/src/swarm.rs:305 logs at Temporary(TempPath { path_buf: "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/722529ca1f3ec4277930408d0694d007", persist: false })
INFO 2020-05-12 04:50:19 storage/libradb/src/lib.rs:163 Opened LibraDB at "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/293991a9c554355e3d0d78674eb8335f/libradb" in 94 ms
INFO 2020-05-12 04:50:19 execution/executor/src/db_bootstrapper.rs:138 Genesis calculated: ledger_info_with_sigs V0(LedgerInfoWithV0 { ledger_info: LedgerInfo { commit_info: BlockInfo { epoch: 0, round: 0, id: HashValue(0000000000000000000000000000000000000000000000000000000000000000), executed_state_id: HashValue(fbad9813e58f44b4d957220968afa722d20f7d819dbd56a0bcedb06f68fce25b), version: 0, timestamp_usecs: 0, next_epoch_info: Some(EpochInfo { epoch: 1, verifier: ValidatorVerifier { address_to_validator_info: {5942d356f114089d4a46f2f3b0b15b52: ValidatorConsensusInfo { public_key: Ed25519PublicKey(1b14e0767993630a34eb6e9f2bd38a240baf870bfaea25797525b6442d3d0b1a), voting_power: 1 }}, quorum_voting_power: 1, total_voting_power: 1 } }) }, consensus_data_hash: HashValue(0000000000000000000000000000000000000000000000000000000000000000) }, signatures: {} }), waypoint Waypoint { version: 0, value: HashValue(ebd5ba79927cf1a3a5ef5d644e38662929f53e4943d0b42cda73353bba5c3df5) }
INFO 2020-05-12 04:50:19 execution/executor/src/db_bootstrapper.rs:72 Genesis commited.
INFO 2020-05-12 04:50:19 common/workspace-builder/src/lib.rs:16 Building project binaries
INFO 2020-05-12 04:50:19 common/workspace-builder/src/lib.rs:30 Finished building project binaries
Wait for startup attempt: 0 of 120
Health check on node '0'
Error querying metrics for node '0'
Wait for startup attempt: 1 of 120
Health check on node '0'
Node '0' is healthy
INFO 2020-05-12 04:50:20 libra-swarm/src/swarm.rs:370 Successfully launched Swarm
To run the Libra CLI client in a separate process and connect to the validator nodes you just spawned, use this command:
	cargo run --bin cli -- -u http://localhost:50819 -m "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/722529ca1f3ec4277930408d0694d007/mint.key"
To run transaction generator run:
	cargo run -p cluster-test -- --mint-file "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/722529ca1f3ec4277930408d0694d007/mint.key" --swarm --peers "localhost:50819" --emit-tx --workers-per-ac 1
Loading client...
Exit client.
Exit libra-swarm.
```

Running the exact same command again now gives different behavior sometimes:

```
~/workspace/opensource/libra(testnet) ➜ cargo run -p libra-swarm -- -s
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/libra-swarm -s`
INFO 2020-05-12 04:50:25 libra-swarm/src/swarm.rs:305 logs at Temporary(TempPath { path_buf: "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/001b33e527bacaa0e89adb0ec0b14d00", persist: false })
INFO 2020-05-12 04:50:25 storage/libradb/src/lib.rs:163 Opened LibraDB at "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/bfefa85d6e643e9c9cacea2e84586b41/libradb" in 88 ms
INFO 2020-05-12 04:50:25 execution/executor/src/db_bootstrapper.rs:138 Genesis calculated: ledger_info_with_sigs V0(LedgerInfoWithV0 { ledger_info: LedgerInfo { commit_info: BlockInfo { epoch: 0, round: 0, id: HashValue(0000000000000000000000000000000000000000000000000000000000000000), executed_state_id: HashValue(7651881f94bd099345c1b46466dccffaa80ba7e08124e7d123d744cbf0f64846), version: 0, timestamp_usecs: 0, next_epoch_info: Some(EpochInfo { epoch: 1, verifier: ValidatorVerifier { address_to_validator_info: {5942d356f114089d4a46f2f3b0b15b52: ValidatorConsensusInfo { public_key: Ed25519PublicKey(1b14e0767993630a34eb6e9f2bd38a240baf870bfaea25797525b6442d3d0b1a), voting_power: 1 }}, quorum_voting_power: 1, total_voting_power: 1 } }) }, consensus_data_hash: HashValue(0000000000000000000000000000000000000000000000000000000000000000) }, signatures: {} }), waypoint Waypoint { version: 0, value: HashValue(1f884ec4ecebee4cbf2b7eda8711279ba02eeeb888ec304793bc5a0665f84282) }
INFO 2020-05-12 04:50:25 execution/executor/src/db_bootstrapper.rs:72 Genesis commited.
INFO 2020-05-12 04:50:25 common/workspace-builder/src/lib.rs:16 Building project binaries
INFO 2020-05-12 04:50:26 common/workspace-builder/src/lib.rs:30 Finished building project binaries
Wait for startup attempt: 0 of 120
Health check on node '0'
Error querying metrics for node '0'
Wait for startup attempt: 1 of 120
Health check on node '0'
Node '0' is healthy
INFO 2020-05-12 04:50:27 libra-swarm/src/swarm.rs:370 Successfully launched Swarm
To run the Libra CLI client in a separate process and connect to the validator nodes you just spawned, use this command:
	cargo run --bin cli -- -u http://localhost:50842 -m "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/001b33e527bacaa0e89adb0ec0b14d00/mint.key"
To run transaction generator run:
	cargo run -p cluster-test -- --mint-file "/var/folders/jr/v1nhn0bs54b7xlv3qtjcz2tw0000gn/T/001b33e527bacaa0e89adb0ec0b14d00/mint.key" --swarm --peers "localhost:50842" --emit-tx --workers-per-ac 1
Loading client...
ERROR 2020-05-12 04:50:27 common/crash-handler/src/lib.rs:38 details = '''panicked at 'called `Option::unwrap()` on a `None` value', client/cli/src/main.rs:85:9'''
backtrace = '''
   0:        0x106db65fd - backtrace::backtrace::trace_unsynchronized::h70247dd9f902890e
   1:        0x106db6583 - backtrace::backtrace::trace::h916980c7a179716e
   2:        0x106dac247 - backtrace::capture::Backtrace::create::h044f52b53a5ef629
   3:        0x106dac186 - backtrace::capture::Backtrace::new::ha010b4c7760599b4
   4:        0x106d9d0b7 - crash_handler::handle_panic::h9253a09473b3b39f
   5:        0x106d9d978 - crash_handler::setup_panic_handler::{{closure}}::h7cda4a82672852c4
   6:        0x107a6a345 - std::panicking::rust_panic_with_hook::h2db5049a14746a6d
   7:        0x107a69e32 - rust_begin_unwind
   8:        0x107aa053f - core::panicking::panic_fmt::hd7d9261f4286def0
   9:        0x107aa0497 - core::panicking::panic::h651c8e2923fc0ad8
  10:        0x106d0fd37 - core::option::Option<T>::unwrap::h03c7c772028adebe
  11:        0x106cfae9e - cli::main::{{closure}}::hfc7b3170242c0b70
  12:        0x106d0daa7 - core::option::Option<T>::unwrap_or_else::h54fb5380eb4c74ae
  13:        0x106cfe5db - cli::main::h53b4eb05dd02bcdd
  14:        0x106cedc4e - std::rt::lang_start::{{closure}}::h05dbffbf9782d3e1
  15:        0x107a69d38 - std::panicking::try::do_call::h7c88c220bfff6b21
  16:        0x107a71feb - __rust_maybe_catch_panic
  17:        0x107a6a66a - std::rt::lang_start_internal::h94930f81f540a165
  18:        0x106cedc31 - std::rt::lang_start::h2feefef53b217409
  19:        0x106d01202 - main
'''

Exit client.
Exit libra-swarm.
```

**Comment by AntoineMkr** [comment]
Running `cargo run -p libra-swarm` (so without the cli) is working for me, so the problem is comming from the cli somewhere. When runnning  `cargo run --bin cli -- -u http://localhost:39777 -m "/tmp/a14cc3ed3ec51ebef2d6c7705b89207f/mint.key"`:

` Finished dev [unoptimized + debuginfo] target(s) in 0.45s
     Running `target/debug/cli -u 'http://localhost:39777' -m /tmp/a14cc3ed3ec51ebef2d6c7705b89207f/mint.key`
ERROR 2020-05-12 08:26:35 common/crash-handler/src/lib.rs:38 details = '''panicked at 'called `Option::unwrap()` on a `None` value', client/cli/src/main.rs:85:9'''
backtrace = '''
   0:     0x557dbe44718d - backtrace::backtrace::libunwind::trace::h341b90f06a975a0f
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
                           backtrace::backtrace::trace_unsynchronized::h6d8be7db263dfa0b
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   1:     0x557dbe44710e - backtrace::backtrace::trace::hcf00f8db89507382
                               at /home/antmkr/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:53
`

**Comment by davidiw** [comment]
There are a lot of issues in this single issue. For unwrapping a None, the CLI needs to be adjusted such that waypoint is expected and not optional.
