### ISSUE TITLE
[mempool] flaky test shared_mempool_test::test_broadcast_dependencies

### ISSUE THREAD

**Issue by phlip9** [libra/libra#4288]
(posting this here so we don't lose track)

The test `shared_mempool_test::test_broadcast_dependencies` seems to fail somewhat infrequently (about once every 15-45 minutes when running continuously on my laptop).

A failing test with trace logs:

```
$ RUST_BACKTRACE=1 RUST_LOG=trace cargo x test --lib -p libra-mempool -- --nocapture test_broadcast_dependencies

core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9aa7ea5e043e558ac2fc2f8785c47388:0:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9aa7ea5e043e558ac2fc2f8785c47388. Current sequence_number: 0, length: 1, parking lot: 0
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9aa7ea5e043e558ac2fc2f8785c47388:2:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9aa7ea5e043e558ac2fc2f8785c47388. Current sequence_number: 0, length: 2, parking lot: 1
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9aa7ea5e043e558ac2fc2f8785c47388:1:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9aa7ea5e043e558ac2fc2f8785c47388. Current sequence_number: 0, length: 1, parking lot: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: ae650c76, event: PeerStateChange
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8e882a96, event: PeerStateChange
tests/shared_mempool_test.rs:286        deliver_message: peer: ae650c76, num_messages: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: ae650c76, event: Broadcast
tests/shared_mempool_test.rs:304        deliver_message: peer ae650c76 <- msg [ from: 8e882a96, sync_msg: BroadcastTransactionsRequest { request_id: "0_1", transactions: [SignedTransaction { { raw_txn: RawTransaction { sender: 9aa7ea5e043e558ac2fc2f8785c47388, sequence_number: 0, }}}}
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8e882a96, event: NewTransactions
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9aa7ea5e043e558ac2fc2f8785c47388:0:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9aa7ea5e043e558ac2fc2f8785c47388. Current sequence_number: 0, length: 2, parking lot: 0
core_mempool/mempool.rs:221             mempool::get_block: seen_consensus=0, walked=2, seen_after=2, result_size=2, block_size=2
tests/shared_mempool_test.rs:347        deliver_response: peer: 8e882a96
tests/shared_mempool_test.rs:254        wait_for_event: peer: ae650c76, event: ACK
tests/shared_mempool_test.rs:286        deliver_message: peer: 8e882a96, num_messages: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8e882a96, event: Broadcast
tests/shared_mempool_test.rs:304        deliver_message: peer 8e882a96 <- msg [ from: ae650c76, sync_msg: BroadcastTransactionsRequest { request_id: "0_1", transactions: [SignedTransaction { { raw_txn: RawTransaction { sender: 9aa7ea5e043e558ac2fc2f8785c47388, sequence_number: 1, }}}}
tests/shared_mempool_test.rs:254        wait_for_event: peer: ae650c76, event: NewTransactions
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9aa7ea5e043e558ac2fc2f8785c47388:1:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9aa7ea5e043e558ac2fc2f8785c47388. Current sequence_number: 0, length: 3, parking lot: 0
core_mempool/mempool.rs:221             mempool::get_block: seen_consensus=0, walked=3, seen_after=3, result_size=3, block_size=3
tests/shared_mempool_test.rs:347        deliver_response: peer: ae650c76

thread 'tests::shared_mempool_test::test_broadcast_dependencies' panicked at
'did not receive expected broadcast ACK: sync msg: BroadcastTransactionsRequest { request_id: "1_2", transactions: [SignedTransaction {
    { raw_txn: RawTransaction { sender: 9aa7ea5e043e558ac2fc2f8785c47388, sequence_number: 2, }}] } }', mempool/src/tests/shared_mempool_test.rs:367:17

stack backtrace:
   0: backtrace::backtrace::libunwind::try
# .. 
  13: libra_mempool::tests::shared_mempool_test::SharedMempoolNetwork::deliver_response
             at mempool/src/tests/shared_mempool_test.rs:367
  14: libra_mempool::tests::shared_mempool_test::SharedMempoolNetwork::deliver_message
             at mempool/src/tests/shared_mempool_test.rs:332
  15: libra_mempool::tests::shared_mempool_test::test_broadcast_dependencies
             at mempool/src/tests/shared_mempool_test.rs:588
  16: libra_mempool::tests::shared_mempool_test::test_broadcast_dependencies::{{closure}}
             at mempool/src/tests/shared_mempool_test.rs:562
# ..
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
```

A normal passing test with trace logs:

```
$ RUST_BACKTRACE=1 RUST_LOG=trace cargo x test --lib -p libra-mempool -- --nocapture test_broadcast_dependencies

core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9f01707449d85fca5e1c07ad4cf46b42:0:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9f01707449d85fca5e1c07ad4cf46b42. Current sequence_number: 0, length: 1, parking lot: 0
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9f01707449d85fca5e1c07ad4cf46b42:2:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9f01707449d85fca5e1c07ad4cf46b42. Current sequence_number: 0, length: 2, parking lot: 1
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9f01707449d85fca5e1c07ad4cf46b42:1:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9f01707449d85fca5e1c07ad4cf46b42. Current sequence_number: 0, length: 1, parking lot: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: 7ef1d789, event: PeerStateChange
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8743cd69, event: PeerStateChange
tests/shared_mempool_test.rs:286        deliver_message: peer: 7ef1d789, num_messages: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: 7ef1d789, event: Broadcast
tests/shared_mempool_test.rs:304        deliver_message: peer 7ef1d789 <- msg [ from: 8743cd69, sync_msg: BroadcastTransactionsRequest { request_id: "0_1", transactions: [SignedTransaction { { raw_txn: RawTransaction { sender: 9f01707449d85fca5e1c07ad4cf46b42, sequence_number: 0, } } } }
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8743cd69, event: NewTransactions
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9f01707449d85fca5e1c07ad4cf46b42:0:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9f01707449d85fca5e1c07ad4cf46b42. Current sequence_number: 0, length: 2, parking lot: 0
core_mempool/mempool.rs:221             mempool::get_block: seen_consensus=0, walked=2, seen_after=2, result_size=2, block_size=2
tests/shared_mempool_test.rs:347        deliver_response: peer: 8743cd69
tests/shared_mempool_test.rs:254        wait_for_event: peer: 7ef1d789, event: ACK
tests/shared_mempool_test.rs:286        deliver_message: peer: 8743cd69, num_messages: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8743cd69, event: Broadcast
tests/shared_mempool_test.rs:304        deliver_message: peer 8743cd69 <- msg [ from: 7ef1d789, sync_msg: BroadcastTransactionsRequest { request_id: "0_1", transactions: [SignedTransaction { { raw_txn: RawTransaction { sender: 9f01707449d85fca5e1c07ad4cf46b42, sequence_number: 1, } }}}
tests/shared_mempool_test.rs:254        wait_for_event: peer: 7ef1d789, event: NewTransactions
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9f01707449d85fca5e1c07ad4cf46b42:1:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9f01707449d85fca5e1c07ad4cf46b42. Current sequence_number: 0, length: 3, parking lot: 0
core_mempool/mempool.rs:221             mempool::get_block: seen_consensus=0, walked=3, seen_after=3, result_size=3, block_size=3
tests/shared_mempool_test.rs:347        deliver_response: peer: 7ef1d789
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8743cd69, event: ACK
tests/shared_mempool_test.rs:286        deliver_message: peer: 7ef1d789, num_messages: 1
tests/shared_mempool_test.rs:254        wait_for_event: peer: 7ef1d789, event: Broadcast
tests/shared_mempool_test.rs:304        deliver_message: peer 7ef1d789 <- msg [ from: 8743cd69, sync_msg: BroadcastTransactionsRequest { request_id: "1_2", transactions: [SignedTransaction { { raw_txn: RawTransaction { sender: 9f01707449d85fca5e1c07ad4cf46b42, sequence_number: 2, }}}}
tests/shared_mempool_test.rs:254        wait_for_event: peer: 8743cd69, event: NewTransactions
core_mempool/mempool.rs:116             [Mempool] Adding transaction to mempool: 9f01707449d85fca5e1c07ad4cf46b42:2:0
core_mempool/transaction_store.rs:248   [Mempool] txns for account 9f01707449d85fca5e1c07ad4cf46b42. Current sequence_number: 0, length: 3, parking lot: 0
core_mempool/mempool.rs:221             mempool::get_block: seen_consensus=0, walked=3, seen_after=3, result_size=3, block_size=3
tests/shared_mempool_test.rs:347        deliver_response: peer: 8743cd69
tests/shared_mempool_test.rs:254        wait_for_event: peer: 7ef1d789, event: ACK
```

I also had some additional logging in these outputs from this patch:

```patch
diff --git a/mempool/Cargo.toml b/mempool/Cargo.toml
index 3dd72ee98..6b754b8ec 100644
--- a/mempool/Cargo.toml
+++ b/mempool/Cargo.toml
@@ -44,4 +44,4 @@ rand = "0.7.3"
 
 [features]
 default = []
-fuzzing = ["libra-types/fuzzing", "storage-interface/fuzzing"]
+fuzzing = ["libra-types/fuzzing", "storage-interface/fuzzing", "libra-config/fuzzing"]
diff --git a/mempool/src/tests/shared_mempool_test.rs b/mempool/src/tests/shared_mempool_test.rs
index 026a0cb3a..5b5e0aff1 100644
--- a/mempool/src/tests/shared_mempool_test.rs
+++ b/mempool/src/tests/shared_mempool_test.rs
@@ -21,6 +21,7 @@ use futures::{
     StreamExt,
 };
 use libra_config::config::{NetworkConfig, NodeConfig, PeerNetworkId, RoleType, UpstreamConfig};
+use libra_logger::prelude::*;
 use libra_network_address::NetworkAddress;
 use libra_types::{transaction::SignedTransaction, PeerId};
 use network::{
@@ -250,6 +251,12 @@ impl SharedMempoolNetwork {
     }
 
     fn wait_for_event(&mut self, peer_id: &PeerId, event: SharedMempoolNotification) {
+        trace!(
+            "wait_for_event: peer: {}, event: {:?}",
+            peer_id.short_str(),
+            event
+        );
+
         let main_peer_id = self.peer_ids.get(peer_id).unwrap_or(peer_id);
         let subscriber = self.subscribers.get_mut(main_peer_id).unwrap();
         assert_eq!(block_on(subscriber.next()).unwrap(), event);
@@ -276,6 +283,12 @@ impl SharedMempoolNetwork {
         peer: &PeerId,
         num_messages: usize,
     ) -> (Vec<SignedTransaction>, PeerId) {
+        trace!(
+            "deliver_message: peer: {}, num_messages: {}",
+            peer.short_str(),
+            num_messages
+        );
+
         // await broadcast notification
         for _ in 0..num_messages {
             self.wait_for_event(peer, SharedMempoolNotification::Broadcast);
@@ -287,6 +300,14 @@ impl SharedMempoolNetwork {
 
         if let PeerManagerRequest::SendMessage(peer_id, msg) = network_req {
             let sync_msg = lcs::from_bytes(&msg.mdata).unwrap();
+
+            trace!(
+                "deliver_message: peer {} <- msg [ from: {}, sync_msg: {:?} ]",
+                peer.short_str(),
+                peer_id.short_str(),
+                sync_msg
+            );
+
             if let MempoolSyncMsg::BroadcastTransactionsRequest { transactions, .. } = sync_msg {
                 // send it to peer
                 let receiver_network_notif_tx = self.network_notifs_txs.get_mut(&peer_id).unwrap();
@@ -311,7 +332,10 @@ impl SharedMempoolNetwork {
                 self.deliver_response(&peer_id);
                 (transactions, peer_id)
             } else {
-                panic!("did not receive expected BroadcastTransactionsRequest");
+                panic!(
+                    "did not receive expected BroadcastTransactionsRequest: sync_msg: {:?}",
+                    sync_msg
+                );
             }
         } else {
             panic!("peer {:?} didn't broadcast transaction", peer)
@@ -320,6 +344,8 @@ impl SharedMempoolNetwork {
 
     /// delivers broadcast ACK from `peer`
     fn deliver_response(&mut self, peer: &PeerId) {
+        trace!("deliver_response: peer: {}", peer.short_str());
+
         let network_reqs_rx = self.network_reqs_rxs.get_mut(peer).unwrap();
         let network_req = block_on(network_reqs_rx.next()).unwrap();
 
@@ -338,7 +364,10 @@ impl SharedMempoolNetwork {
                 // await ACK delivery
                 self.wait_for_event(&peer_id, SharedMempoolNotification::ACK);
             } else {
-                panic!("did not receive expected broadcast ACK");
+                panic!(
+                    "did not receive expected broadcast ACK: sync msg: {:?}",
+                    sync_msg
+                );
             }
         } else {
             panic!("peer {:?} did not ACK broadcast", peer);
@@ -531,6 +560,8 @@ fn test_broadcast_self_transactions() {
 
 #[test]
 fn test_broadcast_dependencies() {
+    ::libra_logger::Logger::new().environment_only(true).init();
+
     let (mut smp, peers) = SharedMempoolNetwork::bootstrap_validator_network(2, 1);
     let (peer_a, peer_b) = (peers.get(0).unwrap(), peers.get(1).unwrap());
     // Peer A has transactions with sequence numbers 0 and 2
```

**Comment by davidiw** [comment]
is this still an issue?

**Comment by gterzian** [comment]
This might be due to spawning the `process_transaction_broadcast` in a [separate sub-task](https://github.com/diem/diem/blob/c4b2a0bbc827514774c1394924c6311d6720a667/mempool/src/shared_mempool/coordinator.rs#L171)(subordinate to the main coordinator select loop task), which means that in theory an `execute_broadcast` task could run in the main coordinator loop, and result in the sending of a `MempoolSyncMsg::BroadcastTransactionsRequest` before the `MempoolSyncMsg::BroadcastTransactionsResponse` has been sent by the separate `process_transaction_broadcast` task, if the execution of the sub-task is delayed for some reason. 

Have you considered simply running `process_transaction_broadcast` on the main coordinator task? 

Alternatively one could rewrite the tests to allow for additional broadcast transaction requests messages being interleaved with the expected transaction response message.
