### ISSUE TITLE
[Bug] CLI crashes when no command is specified

### ISSUE THREAD

**Issue by koshikraj** [libra/libra#501]
# 🐛 Bug

Libra CLI crashes when returned without any command

## To reproduce
Launch Libra CLI with `./scripts/cli/start_cli_testnet.sh` and press enter without any input

** Stack trace/error message **
```
libra% 
C0810 00:03:29.872706 140340501884160 common/crash_handler/src/lib.rs:36] details = '''panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libcore/slice/mod.rs:2681:10'''
backtrace = '''
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::h445ee6adcbbf9c14 (0x557d6950f62d)
             at /home/koshik/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::h329d0491b418d28c
             at /home/koshik/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace::hd840056719fd9122 (0x557d6950f5ae)
             at /home/koshik/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create::hb53cf1891bc51742 (0x557d695014dd)
             at /home/koshik/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/capture.rs:163
   3: backtrace::capture::Backtrace::new::h197f49e876daa2e6 (0x557d695013d5)
             at /home/koshik/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/capture.rs:127
   4: crash_handler::handle_panic::h4dc6092caf2faf75 (0x557d67c5f48d)
             at common/crash_handler/src/lib.rs:33
```

## Expected Behavior

Throw a command error message

## System information

- Libra commit 05c40c977badf052b9efcc4e0180e3628bee2847

**Comment by mgorven** [comment]
This should be fixed by 32c5974.
