### ISSUE TITLE
[Bug] the TransactionReplayer can't replay a chunk with epoch bumps in the middle.

### ISSUE THREAD

**Issue by msmouse** [libra/libra#6067]
# 🐛 Bug

this flaky smoke test https://app.circleci.com/pipelines/github/libra/libra/30485/workflows/aecc0732-7525-4d9a-affb-beaf6b77f0e9/jobs/211038/parallel-runs/1?filterBy=ALL reveals that the TransactionReplayer can't replay a chunk with epoch bumps in the middle.

## To reproduce
`cargo clean && cargo x test -p smoke-test -- --test smoke_test::test_db_restore --nocapture` 

**Stack trace/error message**
```
thread 'smoke_test::test_db_restore' panicked at 'db-restore failed, output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "INFO 2020-09-17T00:00:45.926645Z secure/push-metrics/src/lib.rs:68 PUSH_METRICS_ENDPOINT env var is not set. Skipping sending metrics.\nINFO 2020-09-17T00:00:46.116402Z storage/libradb/src/lib.rs:162 Opened LibraDB at \"/var/folders/hb/d4b0grts37307v_s4h4z0xwr0000gn/T/06cf8695543fb6db7255db23e6e1451f/0/db/libradb\" in 187 ms\nINFO 2020-09-17T00:00:46.120766Z storage/backup/backup-cli/src/coordinators/restore.rs:52 Restore coordinator started.\nINFO 2020-09-17T00:00:46.123303Z storage/backup/backup-cli/src/metadata/cache.rs:78 Metadata files listed.\nINFO 2020-09-17T00:00:46.134214Z storage/backup/backup-cli/src/metadata/cache.rs:115 Metadata cache loaded.\nWARN 2020-09-17T00:00:46.134441Z storage/backup/backup-cli/src/coordinators/restore.rs:127 Can\'t find transaction backup containing the target version, will restore as much as possible\nINFO 2020-09-17T00:00:46.134818Z storage/backup/backup-cli/src/coordinators/restore.rs:66 Planned to restore to version 79.\nINFO 2020-09-17T00:00:46.134918Z storage/backup/backup-cli/src/backup_types/epoch_ending/restore.rs:48 Epoch ending restore started. Manifest: epoch_ending_0-.df55/epoch_ending.manifest\nINFO 2020-09-17T00:00:46.140263Z storage/backup/backup-cli/src/backup_types/epoch_ending/restore.rs:55 Epoch ending restore succeeded.\nINFO 2020-09-17T00:00:46.140415Z storage/backup/backup-cli/src/backup_types/transaction/restore.rs:137 Transaction restore started. Manifest: transaction_0-.26a3/transaction.manifest\nINFO 2020-09-17T00:00:46.169982Z storage/backup/backup-cli/src/backup_types/transaction/restore.rs:194 Replaying transactions 0 to 19.\nERROR 2020-09-17T00:00:46.260034Z storage/backup/backup-cli/src/bin/db-restore.rs:61 main_impl() failed: Transaction restore failed: The 1-th transaction to be commited did not have a status of \'Keep\' but instead had the following status: Retry. \nError: Transaction restore failed: The 1-th transaction to be commited did not have a status of \'Keep\' but instead had the following status: Retry. \n" }', testsuite/smoke-test/src/smoke_test.rs:2239:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by msmouse** [comment]
https://github.com/libra/libra/pull/6078 fixed this
