### ISSUE TITLE
[Bug] Transfer failed with vm status: Validation(UnknownScript)

### ISSUE THREAD

**Issue by srihamat** [libra/libra#715]
# 🐛 Bug

With git pull origin master/testnet
I found failed to perform transaction: Transaction failed with vm status: Validation(UnknownScript)

## To reproduce

** Code snippet to reproduce **
```
$ git pull origin master
$ git checkout testnet
$ ./scripts/cli/start_cli_testnet.sh
Libra% account create
Libra% account create
Libra% account mint 0 1000
Libra% transfer 0 1 200
>> Transferring
[ERROR] Failed to perform transaction: Transaction failed with vm status: Validation(UnknownScript)
```

** Stack trace/error message **
```
>> Transferring
[ERROR] Failed to perform transaction: Transaction failed with vm status: Validation(UnknownScript)
```

## Expected Behavior
>> Transferring
Transaction submitted to validator
To query for transaction status, run: query txn_acc_seq 0 0 <fetch_events=true|false>

## System information

**Please complete the following information:**
- -- Libra Version --
8fd0fb236318e509f76aa45ee8b6a832a6f3d9fc 
- -- Rust Version --
rustc 1.38.0-nightly
- -- Computer OS --
Ubuntu 18.04

## Additional context

By looking at source code validator.rs, the VMValidationStatus:UnknownScript will only failed if it's not came from VM whitelist. Not sure yet if it's related with mismatch configuration that just updated on https://github.com/libra/libra/pull/696, https://github.com/libra/libra/pull/691

I'm going to build local validator with some debug code to see if I can get more information.

**Comment by srihamat** [comment]
build & run docker dev validator found error which loading node config from: node.config.toml
panicked at 'Unable to parse Config: Error ... message: "messing field `network_signing_private_key`

Look like there is also another error mismatch configuration cause wrongly refer to config file that doesn't have field `network_signing_private_key`
I can take a look at it but my laptop is pretty slow on building, it will take some time. 
In the mean time, I will try build single local validator to see if it's possible to catch initiate failure with debug code.

> I0826 10:44:52.104732 140004613420800 common/executable_helpers/src/helpers.rs:27] Loading node config from: node.config.toml
C0826 10:44:52.470565 140004613420800 common/crash_handler/src/lib.rs:36] details = '''panicked at 'Unable to parse Config: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `network_signing_private_key`", key: [] } }', src/libcore/result.rs:999:5'''
backtrace = '''
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::had767f2c8e29e19e (0x564a97eaacb7)
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::h0337158efba408b0
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
      backtrace::backtrace::trace::h065ae1dc8a21d4e1
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:53
   1: backtrace::capture::Backtrace::create::h531150a70b0058dc (0x564a97eaa133)
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/capture.rs:163
      backtrace::capture::Backtrace::new::hb128b44d95056d5b
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/capture.rs:127
   2: crash_handler::handle_panic::haece5e0e7c399820 (0x564a97a45773)
             at common/crash_handler/src/lib.rs:33
   3: crash_handler::setup_panic_handler::{{closure}}::he65be24819485ed5 (0x564a97a456f9)
             at common/crash_handler/src/lib.rs:25
   4: std::panicking::rust_panic_with_hook::h4e9b0b66399f41c3 (0x564a97f851c9)
             at src/libstd/panicking.rs:481
   5: std::panicking::continue_panic_fmt::hc70357f1b69b61f2 (0x564a97f84c62)
             at src/libstd/panicking.rs:384
   6: rust_begin_unwind (0x564a97f84b46)
             at src/libstd/panicking.rs:311
   7: core::panicking::panic_fmt::h58293202aee40982 (0x564a97fa200d)
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed::h7308a99d4a0927f7 (0x564a97b72283)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect::h75242e53ae966262 (0x564a97b63299)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libcore/result.rs:827
      config::config::KeyPairs::parse::ha200258e8c1a4862
             at config/src/config.rs:173
  10: config::config::KeyPairs::load_config::h1e0048b79b02dbb5 (0x564a97a3cb7e)
             at /libra/config/src/config.rs:170
      config::config::NodeConfig::load_config::h5a9c8869f582c354
             at /libra/config/src/config.rs:681
  11: executable_helpers::helpers::load_configs_from_args::h73602afaf201198d (0x564a97a3a5b7)
             at common/executable_helpers/src/helpers.rs:28
  12: executable_helpers::helpers::setup_executable::ha670bafe8dc24101 (0x564a97a3b048)
             at common/executable_helpers/src/helpers.rs:78
  13: libra_node::main::hc7c54e7a50988d8a (0x564a96e7b068)
             at libra_node/src/main.rs:32
  14: std::rt::lang_start::{{closure}}::h6b0b23018591c250 (0x564a96e7b433)
             at /rustc/6e310f2abae97323ca1d5469657b83aa1a9407e0/src/libstd/rt.rs:64
  15: std::rt::lang_start_internal::{{closure}}::h97d75582852bd45b (0x564a97f84ae3)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::hd358001485aeb1cd
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic (0x564a97f8972a)
             at src/libpanic_unwind/lib.rs:82
  17: std::panicking::try::h2d5ccee2ed3f74fa (0x564a97f856ad)
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind::h9c102f4007b228cb
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h449549f8f867a3ee
             at src/libstd/rt.rs:48
  18: main (0x564a96e7b428)
  19: __libc_start_main (0x7f555df522e1)
  20: _start (0x564a96e75b6a)
  21: <unknown> (0x0)'''

**Comment by srihamat** [comment]
Note: The problem is not happen when I ran single validator on bench.

> $ cargo run -p libra_swarm -- -s

![image](https://user-images.githubusercontent.com/36180751/63702974-3c891100-c852-11e9-858e-1dd69b07c836.png)

**Comment by srihamat** [comment]
Found that KeyPairs's path is peer_keypairs.config.toml that not existing.
Normally, it suppose to load file 'validator_[peer_id].node.keys.toml' instead.

I will try to modify code as I expected file name then try build and run validator again.

**Comment by srihamat** [comment]
It's 00:10AM in Thailand, I have to go to bed. I will try to look into details again tomorrow if no one fix it yet.

**Comment by srihamat** [comment]
@fbandersnatch ,

Many thanks for information.

I'm not try to work on it but I try to help you guy. :)

Surely, the team with your guidance will make it better soon.
Please let me know if I can help on something as part of the team.

**Comment by srihamat** [comment]
get latest code https://github.com/libra/libra/commit/f901a5888efa4983d9ed568c4cf9a1f5a1ce1cea
Then try

>$ ./scripts/cli/start_cli_testnet.sh

There is difference error found, it become:
Not able to connect to validator at ac.testnet.libra.org:8000, error InvalidSignature

![image](https://user-images.githubusercontent.com/36180751/63833934-56d00580-c99e-11e9-9f42-fc6c211ff88a.png)

Since libra team are still working on getting the config better, I will just come back to see what I can help later.

**Comment by srihamat** [comment]
Dear @fbandersnatch,

Many thanks for information.

My original steps to reproduce is similar with https://developers.libra.org/ (with git checkout testnet) but look like now it's not seen original failure with particular steps.

Closed issue as fixed
